# Generated by Django 3.0.7 on 2020-06-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_to_action', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('citation', models.URLField(blank=True)),
            ],
        ),
    ]
