# Generated by Django 3.0.7 on 2020-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
